version:  '3.7'
services:
  db:
    image: mysql
    container_name: db
    ports: 
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: biblioteca
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test 
    volumes:
      - ./backend/mysql:/var/lib/mysql
      - ./backend/conf:/etc/mysql/conf.d
    networks:
      - laravel    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8001:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    networks:
      - laravel
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - db
      - php

    networks:
          - laravel
  php:
    build: './backend'  
    container_name: php
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
  angular:
    image: angular
    build: './frontend/wwwquewey'
    environment: 
      NODE_ENV: production
    ports:
      - 5000:80
networks:
  laravel:
volumes:
  persistent: