version: "3"
services: 
    angular:
        image: angular
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 4201:80
volumes:
  angularngixvolume:
